export const INCREASE_LEVEL = "INCREASE_LEVEL";
export type INCREASE_LEVEL = typeof INCREASE_LEVEL;

export const DECREASE_LEVEL = "DECREASE_LEVEL";
export type DECREASE_LEVEL = typeof DECREASE_LEVEL;
